### ISSUE TITLE
Feature Request/Possible Bug: Allow the user to view event times in their local timezone

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/Code-Connector-Chrome-Extension#1]
Code Connector has a lot of online events, and members are spread across timezones. It would be nice if the chrome extension displayed the event dates and times in a local format relevant to the user. If this is possible automatically, great! If it has to be configured, it would be nice to allow the user to specify their timezone in the extension options.

**Comment by jcsmileyjr** [comment]
Great idea. I'm going to have to investigate. I have never tried to solve this problem before. But now I have a problem to solve this weekend. Yeah!!!!!

**Comment by rjbeers** [comment]
Looks like you are handling the dates and times as strings and not javascript Date instances. If you get your data and treat them as dates, you should be able to display the dates in the browser's timezone.

**Comment by rjbeers** [comment]
Should be fixed with #2 
I'll close this out when I get the latest release installed in Chrome.
